#!/bin/bash
#
# This script takes a Rackspace Cloud account and creates hosted puppet
# infrastructure, plus shared service servers.
#

# Validate configuration
if [ ! -f configuration.bash ]; then
  echo ">>> You must setup configuration.bash!"
  exit 1
else
  source configuration.bash
fi

# Source in shared functions
source shared.bash

# Check if we're already running
checkRunning

# Install packages
installDependencies

# Generate output directory
output_directory=$(getOutputDirectory)

# Sleeping
echo "*** We will run a process that might cause some damage... 5 seconds to CTRL-C!"
sleep 5

for instance in api dashboard datasync db dsa01 dsa02 ldap ns01 ns02 puppet-strings postgresql queue; do
  echo ">>> Launching instance: $instance"
  nova boot "$(getServerName).$data_center.$top_level_domain" --flavor 2 --image "$base_image" > "$output_directory/$instance.txt"
done

echo ">>> Waiting on services..."
waitOnServices

echo ">>> Verifying DNS configuration..."
rackdns domain-show "$top_level_domain" > /dev/null
if [ "$?" -gt 0 ]; then
  echo ">>> Creating top level domain..."
  rackdns domain-create "$top_level_domain" --email-address "$dns_email_address" > /dev/null
fi

echo ">>> Creating DNS entries..."
for server in "$output_directory"/*.txt; do
  id=$(novaValueByKey id "$server")
  name=$(novaValueByKey name "$server")
  ip_address=$(nova show "$id" | novaValueByKey accessIPv4)
  echo ">>> Creating $name ($ip_address)..."
  rackdns record-create --name "$name" --type A --data "$ip_address" "$top_level_domain" > /dev/null
done

# Exit
echo ">>> Infrastructure is done, see $output_directory for details"
finishRunning
exit 0
