#!/bin/bash
#
# This script takes a Rackspace Cloud account and creates a Bitlancer Strings
# base image.
#
# Instructions:
#
# * Spin up a CentOS 6.x server with ius, epel, and puppetlabs repos
# * Grab this directory from git and pop in on said server
# * Run this script
# * Terminate CentOS 6.x server
# * Profit
#

# Source in shared functions and variables
source shared.bash

# Sleeping
echo "*** We will run a process that might cause some damage... 5 seconds to CTRL-C!"
sleep 5

# Launch Infrastructure
echo ">>> Launching template image..."
novaExecute boot "base-image-v$base_image_version" --flavor 2 --image "$template_image" > "$output_directory/base-image.txt"

echo ">>> Waiting on services..."
waitOnServices

# Get variables
id=$(novaValueByKey id "$output_directory/base-image.txt")
password=$(novaValueByKey adminPass "$output_directory/base-image.txt")
ip_address=$(novaExecute show "$id" | novaValueByKey accessIPv4)

echo ">>> Setting up base image..."
ssh -oControlMaster=yes -oControlPath=/tmp/ssh-%r-%h-%p "$ip_address"
sshExecute wget -q http://dl.iuscommunity.org/pub/ius/stable/CentOS/6/x86_64/epel-release-6-5.noarch.rpm http://dl.iuscommunity.org/pub/ius/stable/CentOS/6/x86_64/ius-release-1.0-11.ius.centos6.noarch.rpm http://yum.puppetlabs.com/el/6Server/products/x86_64/puppetlabs-release-6-7.noarch.rpm
sshExecute rpm --nosignature --quiet -i epel-release-6-5.noarch.rpm ius-release-1.0-11.ius.centos6.noarch.rpm puppetlabs-release-6-7.noarch.rpm
sshExecute yum --nogpgcheck -q history new
sshExecute yum --nogpgcheck -q -y update
sshExecute yum --nogpgcheck -q -y install ntp nscd postfix sudo collectd puppet ldap bc bind-utils curl finger gnupg man mlocate nano vi emacs joe patch rsync screen systat telnet unzip git puppet > /dev/null
sshExecute rm epel-release-6-5.noarch.rpm ius-release-1.0-11.ius.centos6.noarch.rpm puppetlabs-release-6-7.noarch.rpm
sshExecute chkconfig puppet --levels 345 on
sshExecute hostname | awk -F'-v' '{ print $2 }' > /etc/base-image-version
sshExecute git clone https://github.com/Bitlancer/rackspace-causeadelay.git
sshExecute mv rackspace-causeadelay/causeadelay /etc/init.d/causeadelay
sshExecute rm -rf rackspace-causeadelay
sshExecute chmod 755 /etc/init.d/causeadelay
sshExecute chown root:root /etc/init.d/causeadelay
sshExecute chkconfig --add causeadelay
sshExecute "puppet_tld=$puppet_tld"; sed -i '/    ssldir = $vardir\/ssl/a\\n    # SRV setup\n    use_srv_records = true\n    srv_domain = $puppet_tld' /etc/puppet/puppet.conf

echo ">>> Snapshotting base image..."
novaExecute image-create --poll "$id" "base-image-v$base_image_version" > /dev/null

echo ">>> Fetching Image ID... "
novaExecute image-list | grep "$id" | awk -F'| ' '{ print $2 }'

echo ">>> Killing base image..."
novaExecute delete "$id"

# Exit
echo ">>> Infrastructure is done, see $output_directory for details"
finishRunning
exit 0
