#!/bin/bash
#
# This script adds a customer to strings by spinning up a puppetdb,
# postgresql, and puppetmaster server in the hosted environment.
#

# Validate configuration
if [ ! -f configuration.bash ]; then
  echo ">>> You must setup configuration.bash!"
  exit 1
else
  source configuration.bash
  echo ">>> Using the following configuration: "
  echo
  echo "    Top Level Domain: $top_level_domain"
  echo "    Data Center: $data_center"
  echo
  echo "    OpenStack Username: $os_username"
  echo "    OpenStack API Key: ********************************"
  echo "    OpenStack Region: $os_region"
  echo
  echo "    Base Image: $base_image"
  echo
  echo "    DNS Email Address: $dns_email_address"
  echo
fi

# Source in shared functions
source shared.bash

# Check if we're already running
checkRunning

# Install packages
installDependencies

# Generate output directory
output_directory=$(getOutputDirectory)

# Sleeping
echo "*** We will run a process that might cause some damage... 5 seconds to CTRL-C!"
sleep 5

for instance in postgresql puppetdb puppetmaster; do
  echo ">>> Launching instance: $instance"
  novaExecute boot "$(getServerName).$data_center.$top_level_domain" --flavor 2 --image "$base_image" > "$output_directory/$instance.txt"
done

echo ">>> Waiting on services..."
waitOnServices

echo ">>> Verifying DNS configuration..."
dnsExecute domain-show "$top_level_domain" > /dev/null
if [ "$?" -gt 0 ]; then
  echo ">>> Creating top level domain..."
  dnsExecute domain-create "$top_level_domain" --email-address "$dns_email_address" > /dev/null
fi

echo ">>> Creating DNS entries..."
for server in "$output_directory"/*.txt; do
  id=$(novaValueByKey id "$server")
  name=$(novaValueByKey name "$server")
  ip_address=$(novaExecute show "$id" | novaValueByKey accessIPv4)
  echo ">>> Creating $name ($ip_address)..."
  dnsExecute record-create --name "$name" --type A --data "$ip_address" "$top_level_domain" > /dev/null
done

# Exit
echo ">>> Infrastructure is done, see $output_directory for details"
finishRunning
exit 0
