#!/bin/bash
#
# This script takes a Rackspace Cloud account and creates a Bitlancer Strings
# base image.
#
# Instructions:
#
# * Spin up a CentOS 6.x server with ius, epel, and puppetlabs repos
# * Grab this directory from git and pop in on said server
# * Run this script
# * Terminate CentOS 6.x server
# * Profit
#

# Source in shared functions and variables
source shared.bash

# Sleeping
echo "*** We will run a process that might cause some damage... 5 seconds to CTRL-C!"
sleep 5

# Launch Infrastructure
echo ">>> Launching template image..."
novaExecute boot "base-image-v$base_image_version" --flavor 2 --image "$template_image" > "$output_directory/base-image.txt"

echo ">>> Sleeping a few minutes to give the APIs a break..."
sleep 200

echo ">>> Checking if we're waiting on services..."
waitOnServices

# Get variables
id=$(novaValueByKey id "$output_directory/base-image.txt")
password=$(novaValueByKey adminPass "$output_directory/base-image.txt")
ip_address=$(novaExecute show "$id" | novaValueByKey accessIPv4)

echo ">>> Setting up base image..."
cat commands/centos-6-x86_64.txt | while read command; do
  echo ">>> Executing: $command"
  sshpass -p "$password" ssh -n -oStrictHostKeyChecking=no "root@$ip_address" "$command"
done

echo ">>> Snapshotting base image..."

# echo ">>> Killing base image..."
# novaExecute delete "$id"

# Exit
echo ">>> Infrastructure is done, see $output_directory for details"
finishRunning
exit 0
